// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
